library identifier: 'pipeline-shared-libs@master', retriever: modernSCM(
        [$class: 'GitSCMSource', remote: 'git@github.com:yogeshrnaik/pipeline-shared-libs.git'])

albAndDnsCreatePipeline { 
    env = "dev"
    vpc = "dev-ecs-workshop"
    user_unique_name = "yogesh"
    github_user_or_org = "yogeshrnaik"
}